global:
  scrape_interval: 5s  # Scrape every 5 seconds

scrape_configs:
  - job_name: 'latencyChecker'
    static_configs:
      - targets: ['host.docker.internal:9090']  # Go service running outside Docker
